version: '2'

services:
  postgresql-master:
    image: 'bitnami/postgresql:15.8.0'
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=testdb
      - ALLOW_EMPTY_PASSWORD=true
      - POSTGRESQL_SHARED_PRELOAD_LIBRARIES=postgis-3
    command: 
      - /bin/sh
      - -c
      - |
        /opt/bitnami/scripts/postgresql/entrypoint.sh /opt/bitnami/scripts/postgresql/run.sh & 
        sleep 10 &&
        psql -U postgres -d testdb -c 'CREATE EXTENSION IF NOT EXISTS postgis;' &&
        wait
 