server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/testdb
    username: postgres
    password: psql

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto:
        none
    properties:
      hibernate:
        '[default_batch_size]': 100
        '[format_sql]': true

  sql:
    init:
      mode: 
        never
      data-locations: classpath:sql/test-data.sql