server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/testdb
    username: postgres
    password: psql

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto:
        create
    properties:
      hibernate:
        '[default_batch_size]': 100
        '[format_sql]': true

  sql:
    init:
      mode: 
        never
      data-locations: classpath:sql/test-data.sql
  security:
    user:
      name: user
      password: password

  web:
    resources:
      static-locations:
      - classpath:/public/
      - classpath:/static/
      - classpath:/resources/
      - classpath:/META-INF/resources/

jwt:
  refresh-token:
    name: refresh-Token
    path: /api/auth/refresh-token
    secret: 89345utgw784htfg89wehruit348123412weitohf23489th
    expiration: 1800 # second
  access-token:
    name: access-Token
    path: /
    secret: 5t289u58y34w895ytgw45y6892374t89u4578ty78y5t893u
    expiration: 600 # second